export const KEYS = {
  // Java
  allCameras: "allCameras",
  departments: "departments",
  checkpoints: "checkpoints",
  entrypoints: "entrypoints",
  entrypoint: "entrypoint",
  entrypointSchedules: "entrypointSchedules",
  logEntersOfEmployees: "logEntersOfEmployees",
  logEntersOfEmployeeById: "logEntersOfEmployeeById",
  logEntersOfEmployeesByStructure: "logEntersOfEmployeesByStructure",
  structureOfOrganizations: "structureOfOrganizations",
  scheduleCameras: "scheduleCameras",
  reportOfEmployees: "reportOfEmployees",
  employeeReport: "employeeReport",
  allSchedules: "allSchedules",
  scheduleOfEntrypoints: "scheduleOfEntrypoints",
  schedulesOfEntrypoints: "schedulesOfEntrypoints",
  ScheduleAndEntrypointOfEmployee: "ScheduleAndEntrypointOfEmployee",
  connectedEmployeesToSchedule: "connectedEmployeesToSchedule",
  jobTrips: "jobTrips",
  logsByOrgUnitCodeAndEntrypointId: "logsByOrgUnitCodeAndEntrypointId",
  // Python

  unitTypes: "unitTypes",
  organizationalUnits: "organizationalUnits",
  positions: "positions",
  positionTypes: "positionTypes",
  workplace: "workplace",
  employeePhoto: "employeePhoto",
  employees: "employees",
  organizationalUnitsChildren: "organizationalUnitsChildren",
  organisation: "organisation",

  // General Auth
  users: "users",
  roles: "roles",
  userProfile: "userProfile",
  permissions: "permissions",
  typeOfPermissions: "typeOfPermissions",
  resources: "resources",
  actions: "actions",
};
